import "dotenv/config";
import { Prisma } from "../src/generated/prisma/client";
import { prisma } from "../src/lib/prisma";

// マスタデータ定義の根拠: 18_Phase3_Detailed_Design.md Part2 / Part3

// 各建物はmetric(ActivityMetricsのキー)とthresholds(レベルごとの閾値、
// 配列の長さ=最大レベル)で成長する。根拠: 18_Phase3 Part2をPhase5で拡張。
// requiredTierは村の発展段階(1:村 2:町 3:都市 4:王国 5:帝国 6:天空帝国)。
// 現在の発展段階以下の建物のみが村画面に出現する(lib/game/settlement.ts参照)。
const buildingMasters = [
  // --- Tier1: 村 ---
  {
    type: "house_small",
    name: "家",
    description: "コミットの積み重ねで発展する住居。",
    metric: "commitCount",
    thresholds: [1, 5, 15, 30, 50],
    flavorTexts: [
      "小さな一軒家が建った。ここから物語が始まる。",
      "壁が塗り替えられ、住み心地が良くなった。",
      "庭に花が咲き、来客が増えてきた。",
      "二階が増築され、家族が集う温かい家に。",
      "村でも評判の立派な一軒家になった。",
    ],
    requiredTier: 1,
    sortOrder: 0,
  },
  {
    type: "house_large",
    name: "大きな家",
    description: "長期的なコミット継続の証となる邸宅。",
    metric: "commitCount",
    thresholds: [50, 100, 200, 400, 800],
    flavorTexts: [
      "手狭だった家が広い邸宅へ生まれ変わった。",
      "使用人を雇えるほどの余裕が生まれた。",
      "客間が増え、来客をもてなせるように。",
      "村随一の豪邸として知られ始めた。",
      "歴史に残る継続の証として語り継がれる邸宅。",
    ],
    requiredTier: 1,
    sortOrder: 1,
  },
  {
    type: "blacksmith",
    name: "鍛冶屋",
    description: "Issue解決の腕が認められた者が集う工房。",
    metric: "issueCloseCount",
    thresholds: [5, 10, 20, 40, 80],
    flavorTexts: [
      "火が灯り、鍛冶屋としての産声を上げた。",
      "打つ音が響き、簡単な道具が作れるように。",
      "腕の良い職人として名が知られ始めた。",
      "難しい依頼も次々とこなす名工房に。",
      "伝説の鍛冶師の工房と称されるまでに。",
    ],
    requiredTier: 1,
    sortOrder: 2,
  },
  {
    type: "guild",
    name: "ギルド",
    description: "多くの課題を解決してきた開発者が集う場所。",
    metric: "issueCloseCount",
    thresholds: [20, 40, 80, 150, 300],
    flavorTexts: [
      "小さな集会所としてギルドが発足した。",
      "課題解決者たちが集うようになった。",
      "依頼が絶えず持ち込まれる人気の場所に。",
      "各地から凄腕の解決人が集うギルドへ。",
      "伝説的な功績を持つギルドとして名を馳せる。",
    ],
    requiredTier: 1,
    sortOrder: 3,
  },
  {
    type: "tavern",
    name: "酒場",
    description: "提案(Pull Request)が飛び交う社交場。",
    metric: "prOpenCount",
    thresholds: [5, 10, 20, 40, 80],
    flavorTexts: [
      "小さな酒場に扉が開いた。",
      "提案が飛び交い、賑わいを見せ始めた。",
      "議論好きの常連客で賑わう人気店に。",
      "新しいアイデアが次々生まれる社交場に。",
      "村の未来を語る名物酒場として知られる。",
    ],
    requiredTier: 1,
    sortOrder: 4,
  },
  {
    type: "dev_base",
    name: "開発拠点",
    description: "マージされた成果が積み上がる開発の中心地。",
    metric: "prMergeCount",
    thresholds: [10, 20, 40, 80, 150],
    flavorTexts: [
      "小さな拠点が開発の一歩を刻んだ。",
      "マージされた成果が積み上がり始めた。",
      "着実な成果で拠点の規模が拡大。",
      "村の開発を牽引する中心地に成長。",
      "数多の成果が結晶した象徴的な拠点へ。",
    ],
    requiredTier: 1,
    sortOrder: 5,
  },
  {
    type: "castle",
    name: "城",
    description: "プレイヤーの総合的な成長を象徴する城。",
    metric: "level",
    thresholds: [10, 20, 30, 50, 100],
    flavorTexts: [
      "小さな砦がその礎を築いた。",
      "城壁が築かれ、村の守りが強まった。",
      "尖塔が加わり、威容を増してきた。",
      "堂々たる城として村を見守る存在に。",
      "プレイヤーの成長を体現する壮麗な城に。",
    ],
    requiredTier: 1,
    sortOrder: 6,
  },
  {
    type: "library",
    name: "図書館",
    description: "学習時間の積み重ねで発展する知識の殿堂。",
    metric: "studyMinutesTotal",
    thresholds: [60, 300, 600, 1200, 3000],
    flavorTexts: [
      "小さな書棚から図書館が始まった。",
      "蔵書が増え、静かな学びの場になった。",
      "多くの学徒が通う知識の拠点に。",
      "貴重な資料も揃う本格的な図書館へ。",
      "知の殿堂と呼ぶにふさわしい姿に。",
    ],
    requiredTier: 1,
    sortOrder: 7,
  },
  {
    type: "academy",
    name: "アカデミー",
    description: "資格取得の実績で発展する教育機関。",
    metric: "qualificationsPassedCount",
    thresholds: [1, 2, 3, 5, 8],
    flavorTexts: [
      "小さな教室でアカデミーが開かれた。",
      "合格者が増え、評判が広がり始めた。",
      "専門的な講義も行われる教育機関に。",
      "多くの有資格者を輩出する名門校へ。",
      "資格取得の聖地として知られるまでに。",
    ],
    requiredTier: 1,
    sortOrder: 8,
  },
  {
    type: "monument",
    name: "記念碑",
    description: "ミッション達成の積み重ねを称える記念碑。",
    metric: "missionsClaimedTotal",
    thresholds: [5, 15, 30, 60, 100],
    flavorTexts: [
      "小さな石碑が最初の達成を刻んだ。",
      "積み重ねた功績が刻まれ始めた。",
      "村人が誇りに思う記念碑になった。",
      "多くの功績を称える大きな碑へ。",
      "村の歴史そのものを物語る記念碑に。",
    ],
    requiredTier: 1,
    sortOrder: 9,
  },

  // --- Tier2: 町 ---
  {
    type: "market",
    name: "市場",
    description: "村を町へと押し上げた交易の証。",
    metric: "commitCount",
    thresholds: [100, 150, 250, 400, 600],
    flavorTexts: [
      "露店が並び、交易が始まった。",
      "商人たちが集まり活気づいてきた。",
      "遠方からも人が訪れる市場に成長。",
      "町の経済を支える一大拠点へ。",
      "近隣一の賑わいを誇る大市場に。",
    ],
    requiredTier: 2,
    sortOrder: 10,
  },
  {
    type: "school",
    name: "学校",
    description: "町の子らが学ぶ、知識拡大の拠点。",
    metric: "studyMinutesTotal",
    thresholds: [500, 1000, 2000, 4000, 8000],
    flavorTexts: [
      "小さな教室で授業が始まった。",
      "生徒が増え、校舎が賑わい始めた。",
      "様々な科目が学べる学校に成長。",
      "町の教育を支える中心的存在に。",
      "優秀な人材を輩出する名門校へ。",
    ],
    requiredTier: 2,
    sortOrder: 11,
  },
  {
    type: "workshop",
    name: "工房",
    description: "職人たちが新しい提案を形にする場所。",
    metric: "prOpenCount",
    thresholds: [30, 50, 80, 120, 180],
    flavorTexts: [
      "小さな作業場に灯りがともった。",
      "職人たちの提案が形になり始めた。",
      "斬新なアイデアが生まれる工房に。",
      "町中から注目される創造の拠点へ。",
      "数々の名作を生み出した工房として名高い。",
    ],
    requiredTier: 2,
    sortOrder: 12,
  },
  {
    type: "watchtower",
    name: "見張り塔",
    description: "町を課題(Issue)から守る監視塔。",
    metric: "issueCloseCount",
    thresholds: [50, 80, 120, 180, 260],
    flavorTexts: [
      "小さな見張り台が建てられた。",
      "課題の兆候をいち早く察知するように。",
      "町の安全を守る頼れる存在に。",
      "遠くまで見渡せる立派な塔へ成長。",
      "町の守護の象徴として讃えられる。",
    ],
    requiredTier: 2,
    sortOrder: 13,
  },

  // --- Tier3: 都市 ---
  {
    type: "cathedral",
    name: "大聖堂",
    description: "資格という名の信仰が集う大聖堂。",
    metric: "qualificationsPassedCount",
    thresholds: [3, 4, 5, 6, 8],
    flavorTexts: [
      "小さな礼拝堂が建立された。",
      "資格という信仰に人々が集い始めた。",
      "荘厳な聖堂として姿を整えてきた。",
      "多くの信者(有資格者)を集める聖地に。",
      "都市を象徴する大聖堂として完成。",
    ],
    requiredTier: 3,
    sortOrder: 14,
  },
  {
    type: "arena",
    name: "闘技場",
    description: "ミッション達成者を称える闘技場。",
    metric: "missionsClaimedTotal",
    thresholds: [40, 60, 90, 130, 180],
    flavorTexts: [
      "小さな闘技場に観客が集い始めた。",
      "ミッション達成者を称える催しが定着。",
      "多くの挑戦者が集う人気の会場に。",
      "町中が熱狂する一大イベント会場へ。",
      "伝説的な達成を称える闘技場として名高い。",
    ],
    requiredTier: 3,
    sortOrder: 15,
  },
  {
    type: "harbor",
    name: "港",
    description: "マージされた成果が世界へ出ていく港。",
    metric: "prMergeCount",
    thresholds: [60, 90, 130, 180, 250],
    flavorTexts: [
      "小さな船着き場ができた。",
      "成果を運ぶ船が行き交い始めた。",
      "多くの交易船が寄港する港に成長。",
      "遠い世界へと成果を届ける拠点へ。",
      "町の繁栄を支える大港として完成。",
    ],
    requiredTier: 3,
    sortOrder: 16,
  },
  {
    type: "observatory",
    name: "天文台",
    description: "プレイヤーの成長を映す天文台。",
    metric: "level",
    thresholds: [15, 20, 25, 30, 40],
    flavorTexts: [
      "小さな望遠鏡が空を見上げ始めた。",
      "成長の軌跡を観測できるようになった。",
      "多くの発見をもたらす天文台に成長。",
      "遠い未来までも見通す施設へ。",
      "プレイヤーの歩みを映す壮大な天文台に。",
    ],
    requiredTier: 3,
    sortOrder: 17,
  },

  // --- Tier4: 王国 ---
  {
    type: "grand_library",
    name: "大図書館",
    description: "王国の叡智を蓄える大図書館。",
    metric: "studyMinutesTotal",
    thresholds: [2000, 3000, 4500, 6500, 9000],
    flavorTexts: [
      "王国の知の礎となる図書館が開館。",
      "蔵書が増え続け、学者が集い始めた。",
      "王国中の叡智が集まる場所に成長。",
      "貴重な文献も揃う一大知識庫へ。",
      "王国の叡智を象徴する大図書館に。",
    ],
    requiredTier: 4,
    sortOrder: 18,
  },
  {
    type: "colosseum",
    name: "大闘技場",
    description: "王国中のコミットを称える大闘技場。",
    metric: "commitCount",
    thresholds: [300, 450, 650, 900, 1200],
    flavorTexts: [
      "王国の威信をかけた闘技場が完成。",
      "コミットの積み重ねを称える催しが人気に。",
      "王国中から観客が集まる会場へ成長。",
      "歴史に残る名勝負が繰り広げられる場に。",
      "王国の誇りを象徴する大闘技場として完成。",
    ],
    requiredTier: 4,
    sortOrder: 19,
  },
  {
    type: "senate",
    name: "元老院",
    description: "課題解決の実績で選ばれし者が集う。",
    metric: "issueCloseCount",
    thresholds: [150, 220, 300, 400, 520],
    flavorTexts: [
      "課題解決の功績者が集う元老院が発足。",
      "重要な議論が交わされる場になった。",
      "王国の意思決定を担う機関へ成長。",
      "多くの功績者が名を連ねる誉れの場に。",
      "王国の英知を結集した元老院として完成。",
    ],
    requiredTier: 4,
    sortOrder: 20,
  },
  {
    type: "shipyard",
    name: "造船所",
    description: "王国の成果を運ぶ船を造る造船所。",
    metric: "prMergeCount",
    thresholds: [150, 220, 300, 400, 520],
    flavorTexts: [
      "王国の造船所が産声を上げた。",
      "マージされた成果を運ぶ船が造られ始めた。",
      "遠洋まで航行できる船を造る技術に成長。",
      "王国の物流を支える一大拠点へ。",
      "世界中に成果を届ける大造船所として完成。",
    ],
    requiredTier: 4,
    sortOrder: 21,
  },

  // --- Tier5: 帝国 ---
  {
    type: "royal_palace",
    name: "王宮",
    description: "帝国の頂点、プレイヤー自身の成長を映す王宮。",
    metric: "level",
    thresholds: [25, 30, 35, 40, 50],
    flavorTexts: [
      "帝国の中心、王宮の礎が築かれた。",
      "壮麗な装飾が施され始めた。",
      "帝国中から人々が仰ぎ見る存在に成長。",
      "王の威光を体現する荘厳な宮殿へ。",
      "プレイヤー自身の到達点を象徴する王宮に。",
    ],
    requiredTier: 5,
    sortOrder: 22,
  },
  {
    type: "great_academy",
    name: "大アカデミー",
    description: "帝国の未来を担う人材を育てる大アカデミー。",
    metric: "qualificationsPassedCount",
    thresholds: [5, 6, 7, 8, 10],
    flavorTexts: [
      "帝国の未来を担う大アカデミーが開校。",
      "優秀な生徒が集まり始めた。",
      "多くの分野の専門家を育てる機関に成長。",
      "帝国中から人材が集う名門へ。",
      "帝国の知の頂点として名を馳せる。",
    ],
    requiredTier: 5,
    sortOrder: 23,
  },
  {
    type: "trade_hub",
    name: "交易拠点",
    description: "帝国中の提案(Pull Request)が集まる交易拠点。",
    metric: "prOpenCount",
    thresholds: [150, 220, 300, 400, 520],
    flavorTexts: [
      "帝国の交易拠点が開設された。",
      "各地からの提案(交易)が集まり始めた。",
      "帝国中の商人が行き交う拠点に成長。",
      "経済の中心地として繁栄を極める。",
      "帝国の富を象徴する一大交易拠点に。",
    ],
    requiredTier: 5,
    sortOrder: 24,
  },
  {
    type: "monastery",
    name: "大修道院",
    description: "ミッションの積み重ねを見守る大修道院。",
    metric: "missionsClaimedTotal",
    thresholds: [100, 140, 190, 250, 320],
    flavorTexts: [
      "静寂に包まれた大修道院が建立された。",
      "ミッションの積み重ねを見守り始めた。",
      "多くの修行者が集う場所へ成長。",
      "帝国中から信仰を集める存在に。",
      "積み重ねた努力の全てを見守る聖域に。",
    ],
    requiredTier: 5,
    sortOrder: 25,
  },

  // --- Tier6: 天空帝国 ---
  {
    type: "imperial_capital",
    name: "帝都",
    description: "天空帝国の中心、プレイヤーの集大成である帝都。",
    metric: "level",
    thresholds: [40, 50, 60, 75, 100],
    flavorTexts: [
      "天空帝国の中心、帝都の建設が始まった。",
      "壮大な街並みが形成され始めた。",
      "天空帝国中から人々が集う中心地に成長。",
      "天空帝国の威信を体現する都市へ。",
      "プレイヤーの集大成たる帝都が完成した。",
    ],
    requiredTier: 6,
    sortOrder: 26,
  },
  {
    type: "world_tree",
    name: "世界樹",
    description: "天空帝国中の学びが集う世界樹。",
    metric: "studyMinutesTotal",
    thresholds: [6000, 9000, 13000, 18000, 25000],
    flavorTexts: [
      "小さな苗木が世界樹として芽吹いた。",
      "枝葉が伸び、多くの学びを受け止め始めた。",
      "天空帝国中の知恵が集う神聖な樹に成長。",
      "天まで届くほどの大樹へと育った。",
      "天空帝国中の学びが集う世界樹として完成。",
    ],
    requiredTier: 6,
    sortOrder: 27,
  },
  {
    type: "grand_colosseum",
    name: "世界闘技場",
    description: "天空帝国を挙げてコミットを称える世界闘技場。",
    metric: "commitCount",
    thresholds: [800, 1200, 1700, 2400, 3200],
    flavorTexts: [
      "天空帝国を挙げての世界闘技場が開場した。",
      "コミットの偉業を称える催しが定着。",
      "世界中から挑戦者が集う舞台に成長。",
      "天空帝国の威信をかけた大会が行われる場に。",
      "天空帝国を挙げてコミットを称える象徴として完成。",
    ],
    requiredTier: 6,
    sortOrder: 28,
  },
  {
    type: "throne_room",
    name: "玉座の間",
    description: "天帝が全ての達成を見守る玉座の間。",
    metric: "missionsClaimedTotal",
    thresholds: [200, 280, 380, 500, 650],
    flavorTexts: [
      "玉座の間に最初の光が灯った。",
      "積み重ねた達成が記録され始めた。",
      "天帝が全ての功績を見守る場に成長。",
      "数多の達成が刻まれた荘厳な間へ。",
      "天帝が全ての達成を見守る玉座の間として完成。",
    ],
    requiredTier: 6,
    sortOrder: 29,
  },
];

const fallbackQuests = [
  { title: "READMEを見直す", description: "自分のリポジトリのREADMEを読み返し、誤字や古い情報を1つ直してみましょう。", difficulty: "easy" },
  { title: "小さなリファクタリング", description: "気になっていた関数や変数名を1つ、わかりやすい名前に変更してみましょう。", difficulty: "easy" },
  { title: "テストを1つ追加する", description: "既存の関数に対して、まだ無いテストケースを1つ書いてみましょう。", difficulty: "medium" },
  { title: "Issueを1件起票する", description: "気になっているバグや改善点をIssueとして書き出してみましょう。", difficulty: "easy" },
  { title: "ドキュメントを書く", description: "実装した機能について、簡単な説明をコメントかドキュメントに残しましょう。", difficulty: "easy" },
  { title: "依存パッケージを確認する", description: "package.jsonの依存関係に古いものがないか確認してみましょう。", difficulty: "medium" },
  { title: "小さなバグを1つ直す", description: "放置していた小さな不具合を1つ選んで修正してみましょう。", difficulty: "medium" },
  { title: "直近のコミットを見返す", description: "自分の直近のコミットを見直し、改善できる点を探してみましょう。", difficulty: "easy" },
  { title: "新しいライブラリを調べる", description: "興味のあるライブラリのドキュメントを15分読んでみましょう。", difficulty: "easy" },
  { title: "エラーハンドリングを見直す", description: "1つの関数のエラーハンドリングを見直し、改善してみましょう。", difficulty: "hard" },
  { title: "コミットメッセージを整える", description: "直近のコミットメッセージのルールを見直し、次から使う書式を1つ決めてみましょう。", difficulty: "easy" },
  { title: "未使用コードを削除する", description: "使われていない関数・変数・importを1つ見つけて削除しましょう。", difficulty: "easy" },
  { title: "型定義を見直す", description: "any型や曖昧な型を1箇所選び、より正確な型に直してみましょう。", difficulty: "medium" },
  { title: "CI設定を確認する", description: "CI/CDの設定ファイルを見直し、無駄なステップがないか確認しましょう。", difficulty: "medium" },
  { title: "セキュリティ設定を見直す", description: "環境変数や秘密情報の管理方法に問題がないか確認しましょう。", difficulty: "hard" },
  { title: "パフォーマンスを計測する", description: "気になっている処理の実行時間を計測し、ボトルネックを探してみましょう。", difficulty: "hard" },
  { title: "コードレビューをする", description: "自分の過去のコードを読み返し、改善点を1つコメントとして書き出してみましょう。", difficulty: "medium" },
  { title: "アクセシビリティを確認する", description: "画面の色コントラストやキーボード操作を1つチェックしてみましょう。", difficulty: "medium" },
  { title: "ログ出力を整理する", description: "デバッグ用に残っていた不要なconsole.logやprintを削除しましょう。", difficulty: "easy" },
  { title: "コミット単位を見直す", description: "1つの大きな変更を、意味のある小さなコミットに分ける練習をしてみましょう。", difficulty: "medium" },
];

// unlockConditionがnullの実績は、コード側のイベントフラグ(isFirstSyncなど)で判定する。
// それ以外は lib/game/unlockConditions.ts の指標(UnlockMetric)に対する
// しきい値判定(metric >= value)で自動アンロックされる。
// rarityは一覧画面での表示(バッジの色・エフェクト)にのみ使う付随情報。
const achievementMasters = [
  {
    type: "first_sync",
    name: "はじめの一歩",
    condition: "初回のGitHub同期を完了する",
    unlockCondition: Prisma.JsonNull,
    rarity: "bronze",
  },
  // --- 継続(longestStreak) ---
  {
    type: "streak_7",
    name: "習慣化",
    condition: "最長連続活動日数が7日以上になる",
    unlockCondition: { metric: "longestStreak", operator: ">=", value: 7 },
    rarity: "bronze",
  },
  {
    type: "streak_30",
    name: "不屈の継続者",
    condition: "最長連続活動日数が30日以上になる",
    unlockCondition: { metric: "longestStreak", operator: ">=", value: 30 },
    rarity: "silver",
  },
  {
    type: "streak_100",
    name: "生ける伝説",
    condition: "最長連続活動日数が100日以上になる",
    unlockCondition: { metric: "longestStreak", operator: ">=", value: 100 },
    rarity: "platinum",
  },
  // --- コミット(commitCount) ---
  {
    type: "commit_100",
    name: "百の頂",
    condition: "累計コミット数が100件以上になる",
    unlockCondition: { metric: "commitCount", operator: ">=", value: 100 },
    rarity: "bronze",
  },
  {
    type: "commit_500",
    name: "コミットの化身",
    condition: "累計コミット数が500件以上になる",
    unlockCondition: { metric: "commitCount", operator: ">=", value: 500 },
    rarity: "silver",
  },
  {
    type: "commit_1000",
    name: "千の刻印",
    condition: "累計コミット数が1000件以上になる",
    unlockCondition: { metric: "commitCount", operator: ">=", value: 1000 },
    rarity: "gold",
  },
  // --- Issueクローズ(issueCloseCount) ---
  {
    type: "issue_close_10",
    name: "課題への一歩",
    condition: "累計Issueクローズ数が10件以上になる",
    unlockCondition: { metric: "issueCloseCount", operator: ">=", value: 10 },
    rarity: "bronze",
  },
  {
    type: "issue_close_50",
    name: "課題解決人",
    condition: "累計Issueクローズ数が50件以上になる",
    unlockCondition: { metric: "issueCloseCount", operator: ">=", value: 50 },
    rarity: "silver",
  },
  {
    type: "issue_close_150",
    name: "問題撲滅者",
    condition: "累計Issueクローズ数が150件以上になる",
    unlockCondition: { metric: "issueCloseCount", operator: ">=", value: 150 },
    rarity: "gold",
  },
  // --- PR作成(prOpenCount) ---
  {
    type: "pr_open_10",
    name: "提案者の証",
    condition: "累計Pull Request作成数が10件以上になる",
    unlockCondition: { metric: "prOpenCount", operator: ">=", value: 10 },
    rarity: "bronze",
  },
  {
    type: "pr_open_50",
    name: "提案の達人",
    condition: "累計Pull Request作成数が50件以上になる",
    unlockCondition: { metric: "prOpenCount", operator: ">=", value: 50 },
    rarity: "silver",
  },
  {
    type: "pr_open_150",
    name: "議論の中心",
    condition: "累計Pull Request作成数が150件以上になる",
    unlockCondition: { metric: "prOpenCount", operator: ">=", value: 150 },
    rarity: "gold",
  },
  // --- PRマージ(prMergeCount) ---
  {
    type: "pr_merge_10",
    name: "マージ職人",
    condition: "累計Pull Requestマージ数が10件以上になる",
    unlockCondition: { metric: "prMergeCount", operator: ">=", value: 10 },
    rarity: "bronze",
  },
  {
    type: "pr_merge_50",
    name: "マージの達人",
    condition: "累計Pull Requestマージ数が50件以上になる",
    unlockCondition: { metric: "prMergeCount", operator: ">=", value: 50 },
    rarity: "silver",
  },
  {
    type: "pr_merge_150",
    name: "統合の覇者",
    condition: "累計Pull Requestマージ数が150件以上になる",
    unlockCondition: { metric: "prMergeCount", operator: ">=", value: 150 },
    rarity: "gold",
  },
  // --- 学習時間(studyMinutesTotal) ---
  {
    type: "study_600",
    name: "勉強家",
    condition: "累計学習時間が600分(10時間)以上になる",
    unlockCondition: { metric: "studyMinutesTotal", operator: ">=", value: 600 },
    rarity: "bronze",
  },
  {
    type: "study_3000",
    name: "知識の探究者",
    condition: "累計学習時間が3000分(50時間)以上になる",
    unlockCondition: { metric: "studyMinutesTotal", operator: ">=", value: 3000 },
    rarity: "silver",
  },
  {
    type: "study_6000",
    name: "賢者の境地",
    condition: "累計学習時間が6000分(100時間)以上になる",
    unlockCondition: { metric: "studyMinutesTotal", operator: ">=", value: 6000 },
    rarity: "gold",
  },
  // --- 資格合格(qualificationsPassedCount) ---
  {
    type: "qualification_1",
    name: "有資格者",
    condition: "資格に1件以上合格する",
    unlockCondition: { metric: "qualificationsPassedCount", operator: ">=", value: 1 },
    rarity: "bronze",
  },
  {
    type: "qualification_5",
    name: "資格コレクター",
    condition: "資格に5件以上合格する",
    unlockCondition: { metric: "qualificationsPassedCount", operator: ">=", value: 5 },
    rarity: "silver",
  },
  {
    type: "qualification_10",
    name: "資格の頂",
    condition: "資格に10件以上合格する",
    unlockCondition: { metric: "qualificationsPassedCount", operator: ">=", value: 10 },
    rarity: "gold",
  },
  // --- ミッション累計達成(missionsClaimedTotal) ---
  {
    type: "mission_10",
    name: "ミッション初心者卒業",
    condition: "ミッション累計達成数が10件以上になる",
    unlockCondition: { metric: "missionsClaimedTotal", operator: ">=", value: 10 },
    rarity: "bronze",
  },
  {
    type: "mission_50",
    name: "ミッションマスター",
    condition: "ミッション累計達成数が50件以上になる",
    unlockCondition: { metric: "missionsClaimedTotal", operator: ">=", value: 50 },
    rarity: "silver",
  },
  {
    type: "mission_100",
    name: "ミッションの覇者",
    condition: "ミッション累計達成数が100件以上になる",
    unlockCondition: { metric: "missionsClaimedTotal", operator: ">=", value: 100 },
    rarity: "gold",
  },
  // --- 村の発展段階(villageTier) ---
  {
    type: "village_tier_town",
    name: "町の礎",
    condition: "村が町以上に発展する",
    unlockCondition: { metric: "villageTier", operator: ">=", value: 2 },
    rarity: "bronze",
  },
  {
    type: "village_tier_bigtown",
    name: "都市の礎",
    condition: "村が都市以上に発展する",
    unlockCondition: { metric: "villageTier", operator: ">=", value: 3 },
    rarity: "silver",
  },
  {
    type: "village_tier_empire",
    name: "王国の礎",
    condition: "村が王国以上に発展する",
    unlockCondition: { metric: "villageTier", operator: ">=", value: 4 },
    rarity: "silver",
  },
  {
    type: "village_tier_kingdom",
    name: "帝国の礎",
    condition: "村が帝国以上に発展する",
    unlockCondition: { metric: "villageTier", operator: ">=", value: 5 },
    rarity: "gold",
  },
  {
    type: "village_tier_nation",
    name: "建国者",
    condition: "村が天空帝国(最終形態)まで発展する",
    unlockCondition: { metric: "villageTier", operator: ">=", value: 6 },
    rarity: "platinum",
  },
  // --- プレイヤーレベル(level) ---
  {
    type: "level_10",
    name: "芽生えし才能",
    condition: "プレイヤーレベル10に到達する",
    unlockCondition: { metric: "level", operator: ">=", value: 10 },
    rarity: "bronze",
  },
  {
    type: "level_20",
    name: "熟練の証",
    condition: "プレイヤーレベル20に到達する",
    unlockCondition: { metric: "level", operator: ">=", value: 20 },
    rarity: "silver",
  },
  {
    type: "level_50",
    name: "頂への到達",
    condition: "プレイヤーレベル50に到達する",
    unlockCondition: { metric: "level", operator: ">=", value: 50 },
    rarity: "platinum",
  },
  // --- クエスト完了数(questCompletedCount) ---
  {
    type: "quest_10",
    name: "クエストの担い手",
    condition: "完了済みクエスト数が10件以上になる",
    unlockCondition: { metric: "questCompletedCount", operator: ">=", value: 10 },
    rarity: "bronze",
  },
  {
    type: "quest_30",
    name: "継続は力なり",
    condition: "完了済みクエスト数が30件以上になる",
    unlockCondition: { metric: "questCompletedCount", operator: ">=", value: 30 },
    rarity: "silver",
  },
  {
    type: "quest_100",
    name: "クエストの覇者",
    condition: "完了済みクエスト数が100件以上になる",
    unlockCondition: { metric: "questCompletedCount", operator: ">=", value: 100 },
    rarity: "gold",
  },
];

const titleMasters = [
  {
    type: "novice",
    name: "駆け出し冒険者",
    condition: "はじめから装着できる称号",
    unlockCondition: { metric: "level", operator: ">=", value: 1 },
    rarity: "bronze",
  },
  {
    type: "apprentice",
    name: "見習い開発者",
    condition: "プレイヤーレベル5に到達する",
    unlockCondition: { metric: "level", operator: ">=", value: 5 },
    rarity: "bronze",
  },
  {
    type: "journeyman",
    name: "一人前の開発者",
    condition: "プレイヤーレベル10に到達する",
    unlockCondition: { metric: "level", operator: ">=", value: 10 },
    rarity: "silver",
  },
  {
    type: "veteran",
    name: "熟練エンジニア",
    condition: "プレイヤーレベル20に到達する",
    unlockCondition: { metric: "level", operator: ">=", value: 20 },
    rarity: "gold",
  },
  {
    type: "legend",
    name: "伝説の開発者",
    condition: "プレイヤーレベル30に到達する",
    unlockCondition: { metric: "level", operator: ">=", value: 30 },
    rarity: "gold",
  },
  {
    type: "grandmaster",
    name: "覚醒せし者",
    condition: "プレイヤーレベル50に到達する",
    unlockCondition: { metric: "level", operator: ">=", value: 50 },
    rarity: "platinum",
  },
  {
    type: "streak_keeper",
    name: "継続の探求者",
    condition: "最長連続活動日数が14日以上になる",
    unlockCondition: { metric: "longestStreak", operator: ">=", value: 14 },
    rarity: "silver",
  },
  {
    type: "iron_will",
    name: "不屈の意志",
    condition: "最長連続活動日数が30日以上になる",
    unlockCondition: { metric: "longestStreak", operator: ">=", value: 30 },
    rarity: "gold",
  },
  {
    type: "timeless",
    name: "刻を超えし者",
    condition: "最長連続活動日数が100日以上になる",
    unlockCondition: { metric: "longestStreak", operator: ">=", value: 100 },
    rarity: "platinum",
  },
  {
    type: "bookworm",
    name: "知識の探求者",
    condition: "累計学習時間が1000分以上になる",
    unlockCondition: { metric: "studyMinutesTotal", operator: ">=", value: 1000 },
    rarity: "silver",
  },
  {
    type: "sage",
    name: "叡智の探求者",
    condition: "累計学習時間が5000分以上になる",
    unlockCondition: { metric: "studyMinutesTotal", operator: ">=", value: 5000 },
    rarity: "gold",
  },
  {
    type: "certified_hunter",
    name: "資格ハンター",
    condition: "資格に3件以上合格する",
    unlockCondition: { metric: "qualificationsPassedCount", operator: ">=", value: 3 },
    rarity: "silver",
  },
  {
    type: "qualification_sage",
    name: "資格の賢者",
    condition: "資格に8件以上合格する",
    unlockCondition: { metric: "qualificationsPassedCount", operator: ">=", value: 8 },
    rarity: "gold",
  },
  {
    type: "mission_ace",
    name: "ミッションの達人",
    condition: "ミッション累計達成数が30件以上になる",
    unlockCondition: { metric: "missionsClaimedTotal", operator: ">=", value: 30 },
    rarity: "silver",
  },
  {
    type: "mission_paragon",
    name: "使命の体現者",
    condition: "ミッション累計達成数が80件以上になる",
    unlockCondition: { metric: "missionsClaimedTotal", operator: ">=", value: 80 },
    rarity: "gold",
  },
  {
    type: "commit_engraver",
    name: "刻み手",
    condition: "累計コミット数が300件以上になる",
    unlockCondition: { metric: "commitCount", operator: ">=", value: 300 },
    rarity: "silver",
  },
  {
    type: "issue_resolver",
    name: "解決屋",
    condition: "累計Issueクローズ数が80件以上になる",
    unlockCondition: { metric: "issueCloseCount", operator: ">=", value: 80 },
    rarity: "silver",
  },
  {
    type: "merge_artisan",
    name: "統合の匠",
    condition: "累計Pull Requestマージ数が50件以上になる",
    unlockCondition: { metric: "prMergeCount", operator: ">=", value: 50 },
    rarity: "silver",
  },
  {
    type: "quest_paragon",
    name: "冒険者の鑑",
    condition: "完了済みクエスト数が50件以上になる",
    unlockCondition: { metric: "questCompletedCount", operator: ">=", value: 50 },
    rarity: "gold",
  },
  {
    type: "founding_ruler",
    name: "建国の王",
    condition: "村が天空帝国(最終形態)まで発展する",
    unlockCondition: { metric: "villageTier", operator: ">=", value: 6 },
    rarity: "platinum",
  },
];

const missionMasters = [
  {
    type: "daily_commit_2",
    name: "今日はコミットを2回",
    description: "今日中に2回コミットしましょう。",
    period: "daily",
    metric: "commitCount",
    targetValue: 2,
    expReward: 15,
  },
  {
    type: "daily_issue_close_1",
    name: "今日はIssueを1件クローズ",
    description: "今日中にIssueを1件クローズしましょう。",
    period: "daily",
    metric: "issueCloseCount",
    targetValue: 1,
    expReward: 20,
  },
  {
    type: "daily_pr_open_1",
    name: "今日はPRを1件作成",
    description: "今日中にPull Requestを1件作成しましょう。",
    period: "daily",
    metric: "prOpenCount",
    targetValue: 1,
    expReward: 15,
  },
  {
    type: "daily_pr_merge_1",
    name: "今日はPRを1件マージ",
    description: "今日中にPull Requestを1件マージしましょう。",
    period: "daily",
    metric: "prMergeCount",
    targetValue: 1,
    expReward: 20,
  },
  {
    type: "daily_study_30",
    name: "今日は30分学習",
    description: "今日中に合計30分以上学習しましょう。",
    period: "daily",
    metric: "studyMinutes",
    targetValue: 30,
    expReward: 15,
  },
  {
    type: "weekly_commit_10",
    name: "今週はコミットを10回",
    description: "今週中に合計10回コミットしましょう。",
    period: "weekly",
    metric: "commitCount",
    targetValue: 10,
    expReward: 50,
  },
  {
    type: "weekly_pr_merge_3",
    name: "今週はPRを3件マージ",
    description: "今週中にPull Requestを3件マージしましょう。",
    period: "weekly",
    metric: "prMergeCount",
    targetValue: 3,
    expReward: 80,
  },
  {
    type: "weekly_issue_close_3",
    name: "今週はIssueを3件クローズ",
    description: "今週中にIssueを3件クローズしましょう。",
    period: "weekly",
    metric: "issueCloseCount",
    targetValue: 3,
    expReward: 60,
  },
  {
    type: "weekly_pr_open_5",
    name: "今週はPRを5件作成",
    description: "今週中にPull Requestを5件作成しましょう。",
    period: "weekly",
    metric: "prOpenCount",
    targetValue: 5,
    expReward: 60,
  },
  {
    type: "weekly_study_180",
    name: "今週は180分学習",
    description: "今週中に合計180分(3時間)以上学習しましょう。",
    period: "weekly",
    metric: "studyMinutes",
    targetValue: 180,
    expReward: 70,
  },
  // --- ボス/ダンジョン(週替わりの高難度ミッション) ---
  {
    type: "boss_bug_overlord",
    name: "バグの大魔王",
    description: "今週20回コミットして、大魔王の弱点を突きましょう。",
    period: "boss",
    metric: "commitCount",
    targetValue: 20,
    expReward: 150,
  },
  {
    type: "boss_issue_giant",
    name: "課題の巨人",
    description: "今週8件のIssueをクローズし、巨大な課題を打ち倒しましょう。",
    period: "boss",
    metric: "issueCloseCount",
    targetValue: 8,
    expReward: 180,
  },
  {
    type: "boss_review_gatekeeper",
    name: "レビュー地獄の番人",
    description: "今週6件のPRをマージし、番人を突破しましょう。",
    period: "boss",
    metric: "prMergeCount",
    targetValue: 6,
    expReward: 220,
  },
  {
    type: "boss_sleepless_sage",
    name: "不眠の賢者",
    description: "今週300分学習し、賢者の試練を乗り越えましょう。",
    period: "boss",
    metric: "studyMinutes",
    targetValue: 300,
    expReward: 160,
  },
  {
    type: "monthly_commit_40",
    name: "今月はコミットを40回",
    description: "今月中に合計40回コミットしましょう。",
    period: "monthly",
    metric: "commitCount",
    targetValue: 40,
    expReward: 150,
  },
  {
    type: "monthly_pr_merge_8",
    name: "今月はPRを8件マージ",
    description: "今月中にPull Requestを8件マージしましょう。",
    period: "monthly",
    metric: "prMergeCount",
    targetValue: 8,
    expReward: 200,
  },
  {
    type: "monthly_study_600",
    name: "今月は600分学習",
    description: "今月中に合計600分(10時間)以上学習しましょう。",
    period: "monthly",
    metric: "studyMinutes",
    targetValue: 600,
    expReward: 180,
  },
];

// difficulty: "easy" | "normal" | "hard" | "expert"。expRewardは難易度に応じて
// 300(easy)/500(normal)/800(hard)/1200(expert)を目安に設定している。
// recommendedOrderはカテゴリ内でのおすすめ学習順(小さいほど先)。
const qualificationMasters = [
  { type: "itpassport", name: "ITパスポート試験", category: "情報処理", difficulty: "easy", recommendedOrder: 1, expReward: 300 },
  { type: "fe", name: "基本情報技術者試験", category: "情報処理", difficulty: "normal", recommendedOrder: 2, expReward: 500 },
  { type: "ap", name: "応用情報技術者試験", category: "情報処理", difficulty: "hard", recommendedOrder: 3, expReward: 800 },
  { type: "sg", name: "情報セキュリティマネジメント試験", category: "情報処理", difficulty: "easy", recommendedOrder: 4, expReward: 300 },
  { type: "sc", name: "情報処理安全確保支援士試験", category: "情報処理", difficulty: "expert", recommendedOrder: 5, expReward: 1200 },
  { type: "java_silver", name: "Java Silver (Oracle Certified Java Programmer, Silver)", category: "Java", difficulty: "normal", recommendedOrder: 10, expReward: 500 },
  { type: "java_gold", name: "Java Gold (Oracle Certified Java Programmer, Gold)", category: "Java", difficulty: "hard", recommendedOrder: 11, expReward: 800 },
  { type: "aws_clf", name: "AWS Certified Cloud Practitioner", category: "AWS", difficulty: "easy", recommendedOrder: 20, expReward: 300 },
  { type: "aws_saa", name: "AWS Certified Solutions Architect - Associate", category: "AWS", difficulty: "normal", recommendedOrder: 21, expReward: 500 },
  { type: "aws_dva", name: "AWS Certified Developer - Associate", category: "AWS", difficulty: "normal", recommendedOrder: 22, expReward: 500 },
  { type: "az900", name: "Microsoft Certified: Azure Fundamentals", category: "Azure", difficulty: "easy", recommendedOrder: 30, expReward: 300 },
  { type: "az204", name: "Microsoft Certified: Azure Developer Associate", category: "Azure", difficulty: "normal", recommendedOrder: 31, expReward: 500 },
  { type: "gcp_ace", name: "Google Cloud Associate Cloud Engineer", category: "GCP", difficulty: "normal", recommendedOrder: 40, expReward: 500 },
  { type: "lpic1", name: "LPIC-1", category: "Linux", difficulty: "normal", recommendedOrder: 50, expReward: 500 },
  { type: "cka", name: "Certified Kubernetes Administrator", category: "Kubernetes", difficulty: "hard", recommendedOrder: 51, expReward: 800 },
  { type: "comptia_security_plus", name: "CompTIA Security+", category: "セキュリティ", difficulty: "normal", recommendedOrder: 60, expReward: 500 },
  { type: "rails_gold", name: "Ruby技術者認定試験 Gold", category: "Ruby", difficulty: "hard", recommendedOrder: 70, expReward: 800 },
  { type: "python_cert", name: "Python 3 エンジニア認定基礎試験", category: "Python", difficulty: "easy", recommendedOrder: 71, expReward: 300 },
  { type: "scrum_master", name: "認定スクラムマスター(CSM)", category: "アジャイル", difficulty: "normal", recommendedOrder: 80, expReward: 500 },
  { type: "pmp", name: "PMP(Project Management Professional)", category: "プロジェクト管理", difficulty: "expert", recommendedOrder: 81, expReward: 1200 },
];

async function main() {
  for (const b of buildingMasters) {
    await prisma.buildingMaster.upsert({
      where: { type: b.type },
      update: b,
      create: b,
    });
  }

  for (const a of achievementMasters) {
    await prisma.achievementMaster.upsert({
      where: { type: a.type },
      update: a,
      create: a,
    });
  }

  for (const t of titleMasters) {
    await prisma.titleMaster.upsert({
      where: { type: t.type },
      update: t,
      create: t,
    });
  }

  for (const m of missionMasters) {
    await prisma.missionMaster.upsert({
      where: { type: m.type },
      update: m,
      create: m,
    });
  }

  for (const q of qualificationMasters) {
    await prisma.qualificationMaster.upsert({
      where: { type: q.type },
      update: q,
      create: q,
    });
  }

  // FallbackQuestはユニークキーを持たないため、毎回全消し→再投入する
  await prisma.fallbackQuest.deleteMany();
  await prisma.fallbackQuest.createMany({ data: fallbackQuests });

  console.log(
    `Seed完了: BuildingMaster ${buildingMasters.length}件 / AchievementMaster ${achievementMasters.length}件 / TitleMaster ${titleMasters.length}件 / MissionMaster ${missionMasters.length}件 / QualificationMaster ${qualificationMasters.length}件 / FallbackQuest ${fallbackQuests.length}件`
  );
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
